language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      env: PY_VERSION=3 MINICONDA_NAME=Miniconda3-latest-Linux-x86_64.sh

install:
    - wget http://repo.continuum.io/miniconda/${MINICONDA_NAME} -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda env create --name notebook-gallery --file environment.yml
    - source activate notebook-gallery

script:
    - |
      # Set up display to be able to plot in linux
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        export DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi
    - |
      if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then
        export CONDA_BUILD_SYSROOT=/
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:/Applications/Xcode.app/Contents//Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
      fi
    - |
      # evaluate example scripts and notebooks on linux only
      if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
        #py.test -v -s examples/*.py;
        py.test -v -s --current-env --nbval-lax */*.ipynb;
      fi
