name: py3_parcels
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.4
  - cachetools>=1.0.0
  - cgen
  - coverage
  - ffmpeg>=3.2.3,<3.2.6
  - flake8>=2.1.0
  - git
  - gcc_linux-64
  - mpi4py>=3.0.1
  - mpich>=3.2.1
  - jupyter
  - matplotlib>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - progressbar2
  - py>=1.4.27
  - pymbolic
  - python-dateutil
  - scipy>=0.16.0
  - six >=1.10.0
  - xarray>=0.10.8
  - cftime
  - dask
  - pytest<4.0
  - nbval
  - scikit-learn
