name: notebook-gallery
channels:
- conda-forge
dependencies:
- bokeh
- bottleneck
- cartopy
- cf-units
- cftime>=1.0.4.2
- cmaps
- cmocean
- dask-jobqueue>=0.7.0
- dask>=2.7
- h5py
- holoviews
- hvplot
- ipywidgets
- jupyterlab
- matplotlib
- metpy
- nbval
- netcdf4
- nodejs
- numba
- pandas
- pip
- pre-commit
- pytest
- scipy
- tqdm
- watermark
- xesmf
- pip:
  - git+https://github.com/pydata/xarray.git
  - git+https://github.com/intake/intake.git
  - git+https://github.com/NCAR/intake-esm.git
  - ncar-jobqueue
  - pooch
  - git+https://github.com/NCAR/notebook-gallery.git#egg=ngallery_utils
